model:
  model_name: "raidium/curia"
  num_classes: 3
# pretrained: '/path/to/project-data/dinov3_weights/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth'
pretrained: '/path/to/project-data/dinov3_weights/CT_2D/final_model.pth'
dataset_name: "raidium/CuriaBench"
dataset_config: "covidx-ct"
use_feature_caching: false
patch_size: 8
img_size: 512
epochs: 10 # 20
batch_size: 64
learning_rate: 0.01 # 0.0002
num_workers: 8
eval_steps: 100
greedy: True
output_dir: "/path/to/project-data/results/covidx-ct/Ours"